name: Bees of Mind
favicon: null
layout_spectrum: 0.22132
typography_spectrum: 0.63837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f1'
    - '#090400'
    - '#95a6ad'
    - '#7a5c19'
    - '#d4a940'
  brandStrength: 0.3125
  lightness: 0.9608831943478435
  saturation: 0.1875
  rhythmicContrast: 0.3081267138477415
purpose: []
