name: Bees of Mind
favicon: null
layout_spectrum: 0.19240935984998941
typography_spectrum: 0.9305180483497679
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.28981442376971245
  lightness: 0.9608831943478435
  saturation: 0.17644351138733327
  rhythmicContrast: 0.3081267138477415
purpose: []
